CXX?=g++
PROG=DCGAN

SOURCES=dcgan_inference.cpp 

LIBS= -ltensorflow-lite -lpthread -ldl -g \
      -lopencv_highgui -lopencv_imgproc -lopencv_core -lopencv_imgcodecs
INC=-I $(SDKTARGETSYSROOT)/usr/include/tensorflow/contrib/lite/tools/make/downloads/flatbuffers/include/ 

all: $(PROG)
	
$(PROG): $(SOURCES)
	$(CXX) -o $@ $(INC) $(DEP_LIBS) $^ $(LIBS)

clean:
	rm -f $(PROG)
